### ISSUE TITLE
Install information 

### ISSUE THREAD

**Issue by Zeyadas** [plateaukao/browser#1]
I'm not familiar with the Way I can install this app on my android tablet, can you help?
I downloaded the Source code but didn't know what to do with it.

**Comment by plateaukao** [comment]
Hi, @Zeyadas 

please download `app-release.apk` from https://github.com/plateaukao/browser/releases/tag/v8.5.1 .
And then you can install the app.

**Comment by Zeyadas** [comment]
Oh. Thanks it works perfectly..
I was wondering if there's something like (KUAL: Kindle Unified Application Launcher) but for Android?
I mean I need a launcher that work on android and make it behave as a dedicated e ink reader.
I found some (actually two) apps:
https://bitbucket.org/dsimbiriatin/simple-ink-launcher/wiki/Home
And the other one is this:
https://m.apkhere.com/app/cn.modificator.launcher and it's not (perfect).

I don't know if I described it clearly..

**Comment by plateaukao** [comment]
What's the issue with the built-in launcher in your android tablet? As far as I know, most Eink device already provided a good launcher for the device, eg, Onyx Boox and Boyue likebook series. That may be why not so many Eink specific launchers developed. :)

**Comment by Zeyadas** [comment]
Oh sorry, forgot to mention that my device is a regular android tablet (Samsung galaxy Tab A 6) (Samsung T-285) with an LCD screen.. 
The built-in launcher is (distracting) with the colors, icons, animations, notifications, and so on..
I liked your browser, its fully featured and basic in the same time and works perfectly, the Samsung browser or Google chrome is distracting for the same reason.

**Comment by plateaukao** [comment]
@Zeyadas 
hm... I got your point. As far as I know, you can try to install Nova launcher, and use simple theme to make most icons black and white; also, disable most animations and hide the status bar. Although need some efforts, but might fit your needs.

**Comment by Zeyadas** [comment]
Sorry for being annoying. The browser worked perfectly on my phone (Samsung galaxy grand prime plus) android 6.0.1 but couldn't install it on my android (5.1.1) tablet, there is a problem parsing the package.

**Comment by plateaukao** [comment]
Hi, @Zeyadas , now it only supports devices newer than SDK level 23, which means Android 6.0. To support lower devices, it may take more effort to verify if the app works well. I may do it in the future. Or, if you know someone who knows how to build Android codes, you can ask him to build the App for you.

**Comment by Zeyadas** [comment]
Oh, thank you.. And I don't know someone who knows how to build Android codes.. I'll wait for you..

**Comment by plateaukao** [comment]
@Zeyadas  it will be supported in next version.

**Comment by Zeyadas** [comment]
I'm so grateful, thank you.
