### ISSUE TITLE
Feature request: webpage copy as text button shortcut

### ISSUE THREAD

**Issue by TukaramUnde** [plateaukao/browser#10]
Please add 'one-tap' whole webpage copy as text button on toolbar.

**Comment by plateaukao** [comment]
Hi, @TukaramUnde 
The feature seems not a common usage for everyone, and you can always select all web page content, and copy it manually. If you really need this feature, suggest you forking this repo and add it in your own repo. :)

**Comment by TukaramUnde** [comment]
Thank you for writing back. As a student, for research, I often need to copy the whole webpage. I've forked this repository and I've no idea what to do next. Please help me.
