### ISSUE TITLE
Menu after copying page text

### ISSUE THREAD

**Issue by xBcai** [plateaukao/browser#103]
It is better to customize the sorting display of this menu. Generally, a dictionary should be installed when reading to facilitate word search, but the original one needs to be clicked twice.

![000](https://user-images.githubusercontent.com/66826351/160225000-82b791ef-7f82-44a4-bd89-236c4a3e0927.jpg)

**Comment by plateaukao** [comment]
@xBcai 
I tried before, but the default order is controlled by system. If I want to manipulate the order, sometimes the actions will be become non-working, or worse, just crash the app. In addition, the usage frequency of each action is different among all users, it's hard to pre-define what actions should be put in the front.
In the future, if I found out a better way to customize the action order, I will work on it again. :) Thanks for the suggestion.
