### ISSUE TITLE
Add option to open WebView options in settings

### ISSUE THREAD

**Issue by Kita2345** [plateaukao/browser#108]

**Comment by plateaukao** [comment]
@Kita2345 what do you mean by open WebView options in Settings?

**Comment by Kita2345** [comment]
See
https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/developer-ui.md#launching-webview-devtools

**Comment by plateaukao** [comment]
@Kita2345 
Thanks. It looks like that you can do so by using command `adb shell am start -a "com.android.webview.SHOW_DEV_UI"` or installing Beta, Dev, Canary version of WebView. I don't know how to add it in EinkBro settings. EinkBro does not include WebView in the app. It uses system's WebView component.

**Comment by plateaukao** [comment]
close due to there's way of doing it from command line.
