### ISSUE TITLE
please create lite app

### ISSUE THREAD

**Issue by BioBut** [plateaukao/browser#11]
reference:
https://github.com/alandau/sweb

**Comment by plateaukao** [comment]
Hi @BioBut 
Thanks for sharing the link. Pull requests are welcomed if you know how to make EinkBro even lighter. 

Now EinkBro only takes about 3MB, among it, around 400KB is adblock domain list. IMHO, it's already very lite comparing to other mainstream browsers, eg., Firefox, Chrome, etc. They usually take more than 50 MB to 100 MB. 

To make EinkBro even lighter, say less than 1MB, I may need to remove all library dependencies, and write my own implementations that are originally provided by external libraries. This takes time, no obvious benefit,  and hard to maintain afterward. 

In brief, this is not a direction EinkBro will put effort on. The purpose of EinkBro is to provid a browser that fits in most Eink devices; not to build the smallest browser. 

If you find sweb(the link you provided) is what you want, you can install it instead, or try to migrate some features from EinkBro to it.

**Comment by BioBut** [comment]
Thank you and fast support 

you can use this browser and improvement 
sweb browser YouTube background play issue, night mode issue, new tab issue (youtube website video running)
