### ISSUE TITLE
Page title bug in history.

### ISSUE THREAD

**Issue by gety9** [plateaukao/browser#117]
Steps to reproduce:

1. Do google search
![Screenshot_20220524-050311](https://user-images.githubusercontent.com/16415882/170001275-ce071565-fba3-4ead-b850-6702e387c24f.png)

2. Open 4 results using "New tab (background)"

3. Titles are correct in tab view
![Screenshot_2022-05-24_05-03-46](https://user-images.githubusercontent.com/16415882/170001631-b2e9bc36-f116-4495-83a1-921987896bba.png)

4. But history has them wrong
![Screenshot_2022-05-24_05-04-20](https://user-images.githubusercontent.com/16415882/170001741-1882a43d-ed4a-421f-9b0c-4af149f1a9fd.png)

I think it's cause history is using "intermediate" search javascript url, instead of final destination url of page itself.

**Comment by plateaukao** [comment]
let me look into the issue. Thanks for reporting it.
