### ISSUE TITLE
Optimize save tabs feature.

### ISSUE THREAD

**Issue by gety9** [plateaukao/browser#118]
I am using "save tabs" feature and most of the time have ~20 tabs open. It works fine until something causes pages to be reloaded (things like turn on / turn off device, sleep / awake device, reconnect physical keyboard, etc) - when it happens eink bro tries to reload ALL pages, which is bad because:

-, it slows down device

-, consumes mobile bandwidth (if you are not on wifi, you pay for it)

To solve this i think we should

-, 1. either cache pages (i think that's how safari on ios works), so they are not reloaded, but this might make eink bro more "heavy", or maybe not? and it's best way to go.

-, 2. or simply reload current tab (only 1 tab, not all), if we go with this route we should just save/show titles in tab view, cause curently it's not clear what page corresponds to this or that tab (for example on this screenshow awake device triggered reload, but internet was off so all tabs have title "Webpage not available" and it's not clear what tab is what page)
![Screenshot_20220524-060847](https://user-images.githubusercontent.com/16415882/170008022-57a0aff5-ef8e-42bf-8cce-176e06ea6db3.png)

**Comment by plateaukao** [comment]
In 0a4f3f91742e44fd664b30f4a07cb6375d4a1fcc , I added a toggle in Settings / BehaviorUI page, to disable background tab loading. This should be your second proposal.

Option 1 is not so feasible for a small app that is casually maintained as a side project. :) I know that Safari, Chrome, and Firefox are all working well, but they are developed by hundreds of developers with full-time job. Caching tab contents offline is out of my reach. I would suggest sending these tabs to other solutions like Pocket service, or save them to a bookmark folder. Once finish reading, just delete these temp bookmarks.

**Comment by gety9** [comment]
@plateaukao sounds great! thank you.

Do i understand it right that it's not added yet in release? (don't see it in latest (v9.0.0))

**Comment by dredmorbius** [comment]
@plateaukao Have you considered Einkbro becoming something other than a small app casually maintained as a side project 😺 

It's a seriously good browser, and address a whole host of massive annoyances _especially_ for web-on-tablet and web-on-eink.  I'm not sure who would be interested in advancing it, though the e-ink device vendors (and probably EInk itself, the company) might.

I've mentioned Einkbro several times to Onyx, strongly positively.

**Comment by plateaukao** [comment]
@gety9 it's not in release yet, cause I need to try it myself for a while. If you wanna try out too, please download the latest build in the bottom of Readme.

@dredmorbius 

So far, no plans to expand it. I still develop it mainly for my personal usage, and practice some techniques I just learned in Android. I have my own tastes of UI and thoughts on user behavior (though it may be a bit too geeky to generic users). I enjoy the process of transforming EinkBro to the way I want it to. 

However, EinkBro is open sourced. If Eink company or even Onyx is interested in it, and would like to extend it more, or adopt most of the features to their existing browser, they are very welcome to do so. I would be very happy to see that happen. A useful built-in browser would be a great plus to existing Eink devices that are equipped with decent CPU.

**Comment by dredmorbius** [comment]
@plateaukao Sometimes scratching your own itch is a great way to satisfy others.  Especially if the interests aren't fully mainstream.

I'm trying hard to avoid the long philosophical discussion, but 1) I've been using (and been frustrated by) Web browsers for over a quarter century and 2) noting that mainstream browser development is getting further and further from actually enabling reading.

It's been a long time since I've been remotely excited about something in this space.  So if I can flatter / bribe / encourage you in any way, I will.

And again:  thanks.  This has been badly needed.

**Comment by plateaukao** [comment]
provided.
