### ISSUE TITLE
Request:  Show link URL on long-press / action tab

### ISSUE THREAD

**Issue by dredmorbius** [plateaukao/browser#119]
Einkbro does not currently show the URL of links being opened, especially on long-press where an option dialogue is offered with the current options:

- New tab (foreground)
- New tab (background)
- Split screen
- Share link
- Open Link with ...

... etc.

Recommendation:  **show the full link URL at the top of the option dialogue**.

See Mozilla Firefox (100.1.3 for example) for an example of a preferable format.

Thanks!

**Comment by plateaukao** [comment]
provided.

**Comment by dredmorbius** [comment]
Thanks, verified, and much appreciated.
