### ISSUE TITLE
Request:  Provide "copy link" option on long-press link dialogue

### ISSUE THREAD

**Issue by dredmorbius** [plateaukao/browser#120]
Copying a link URL presently  requires:

- Long press on link
- Select "Share URL"
- Find "Copy" option.
- Select "Copy"

On Mozilla Firefox / Android (e.g., v. 100.1.3), "copy URL" is the second option on the long-press URL dialogue.

Please provide a "copy link" option on the link action dialogue.

Thanks!

**Comment by plateaukao** [comment]
will do. However, may I know what's the usage of copying the url on a link that is not yet opened? Usually, users will use the share feature to do following actions.

**Comment by dredmorbius** [comment]
I'm old school and prefer to open apps directly myself.

Typically, I'm copying the URL to a specific app and format --- e.g., if I "share" to Firefox / Fennec, the URL opens in Normal mode.  I largely operate in Incognito as a form of tab management (the tabs die with the session).  Normal mode is only for tab sessions I'd like to keep around for a while.

I'm also frequently copying to shell / terminal sessions under Termux.

Or I'll copy and share directly into Pocket, as that workflow is not as multi-step / annoying as the Share action.

**Comment by dredmorbius** [comment]
Feature verified.  Thanks!
