### ISSUE TITLE
Frequent session loss when alternating between Apps on Android

### ISSUE THREAD

**Issue by dredmorbius** [plateaukao/browser#121]
This seems to be a long-standing Android application issue, though Einkbro exhibits it more than most apps in my experience.

If I've opened a number of tabs in Einkbro to cycle through reading, and  happen to switch _even briefly_ to another App ... the entire session is cleared.

I'm noticing this on _both_ Incognito and Normal modes.

Device:  Onyx BOOX Max Lumi / Android 11.

Determining how much Incognito mode history to retain, and when to clear it, is challenging.  I've tended to rely mostly on Incognito for browsing sessions _both_ for (slightly) increased privacy and, far more so, _because manually clearing out sessions is painful_.

This also means I'm frequently saving Incognito Mode sessions to other apps, such as Pocket.  This often results in Einkbro losing a large session (10 -- 50+ tabs opened).

I'd prefer that Incognito mode would retain its current tab state until explicitly quit, device rebooted, or session cleared (UI/UX for this last is ... unclear).  Otherwise, please preserve and protect user state.

**Comment by plateaukao** [comment]
There's an option in Settings > Behavior/UI to allow you save tabs. That will help to keep currently opened tab list. 
The reason why all tabs are gone when you switch to other tabs is because Android system has a mechanism to kill apps that uses a lot of memories to allow foreground app has more memory to use.

**Comment by dredmorbius** [comment]
"Save Tabs" is selected.  That works much of the time but not all.

I'm fairly certain that much of the fault here lies with Android itself.  That said, more robust would be better.

There's another issue which has me quitting and restarting Einkbro fairly often --- when the touch zones for next/previous page are set to "bottom", the actual locations occasionally migrate up the screen.

Setting the value to another option (e.g., "left"), quitting Einkbro, restarting, and setting touch to "bottom", resets this.

The tabs are also virtually always retained.  Even in Incognito.

Mysteries of the Universe ...

**Comment by plateaukao** [comment]
@dredmorbius  for the touch area moving symptom, in fact it's a feature. You can drag left-top corner of the right touch area, and move it up or down to fit your needs.

**Comment by gety9** [comment]
@plateaukao Daniel, hi

I have same issues, but never posted them cause considered them minor, what dredmorbius means is:

-, 1) when "save tabs" is selected it most of them time (98%) works perfect, but sometimes (when you switch between the apps) it starts with 1 tab (as if save tabs never was enabled). I mean say i have 5 tabs open, i switch to another app, then switch back and 4 tabs are lost forever.

-, 2) touch area moving a little bit from it's supposed location. Here is screenshot:
![Screenshot_20220528-083801](https://user-images.githubusercontent.com/16415882/170825839-e35fc681-6860-4851-ae53-a725c6d1676c.png)
You see it moved a little bit down... Sometimes it can move a little up. It's not caused by settings, it always is at "right" setting.

**Comment by gety9** [comment]
> @dredmorbius for the touch area moving symptom, in fact it's a **very hidden** feature. You can drag left-top corner of the right touch area, and move it up or down to fit your needs.

Wow, indeed hidden feature :) I also thought it's a bug :)

**Comment by dredmorbius** [comment]
@plateaukao Is there any possiblity that Einkbro can force a state-save when switching between apps, or when the app selector is highlighted?

So long as I can get my tabs back,  in the same order, I'm reasonably happy.  I'd also prefer *not* losing any text in dialogues, though my use of my E-ink device generally does not include any account-based services, so I'm not, say, losing a comment or post.

That said:  losing comments or posts when switching between apps or browser tabs pretty much precisely sucks, and is a long-standing gripe of mine for numerous Android apps and browsers.

**Comment by plateaukao** [comment]
Once you selected "Save tabs", EinkBro will save these tabs url info no matter you're switching to other apps, or reboot your device. 

The titles in tab list view is obtained when loading each tab url. It's not easy to fix them for just previously  saved tabs. 

10~50 tabs sounds not like a normal use for mobile browser. Webview is very memory consuming; 2 to 5 is still doing well. 10 to 50 tabs will definitely falls in the top list  to be killed by system once you switch to other apps. Even "save tabs" works correctly, EinkBro would have to load all these tabs again when it's brought to foreground again. 

If you could find out exactly  in what flow, all the saved tabs wille be gone, I will look into why it's not working as expected.

**Comment by plateaukao** [comment]
I'll try to add an option not to load background tabs when they are created. In this way, maybe the tab title can be saved correctly and don't use a lot of memories in the beginning, which is the main reason why the APP is so prone to be killed by android system frequently.

**Comment by dredmorbius** [comment]
@plateaukao Lazy-loading was going to be a suggestion of mine.

That's what Firefox does on both Android and Desktop.  Given I have Far Too Many Tabs Open there as well (> 1,500 on desktop last I checked), that ... either helps with the problem or enables my disorder 😺 

Thanks!

**Comment by plateaukao** [comment]
added lazy loading in settings.
