### ISSUE TITLE
The bookmark page disappears one line

### ISSUE THREAD

**Issue by xBcai** [plateaukao/browser#122]
When more than a certain number of bookmarks are saved (the height of the bookmark is higher than the height of the mobile screen in the test), one will be hidden automatically, and it is recommended to add a scroll bar. Thank you.
[15个书签测试220528.txt](https://github.com/plateaukao/browser/files/8790061/15.220528.txt)

**Comment by plateaukao** [comment]
Thank you for reporting this issue. I will re-write the bookmark list UI.
