### ISSUE TITLE
Page-turn Touch Area moves unexpectedly & w/o visual feedback

### ISSUE THREAD

**Issue by dredmorbius** [plateaukao/browser#123]
This is a "feature".  I'd suggest it's a design bug violating the principle of least astonishment:

> @dredmorbius  for the touch area moving symptom, in fact it's a **very hidden** feature. You can drag left-top corner of the right touch area, and move it up or down to fit your needs.

_Originally posted by @plateaukao in https://github.com/plateaukao/browser/issues/121#issuecomment-1138414394_

My expectation if I set the touch area to be at the bottom of the screen is that it _remain_ there.

I typically have the touch-area outlines disabled to minimise visual distraction on the page.  (Reducing visual distractions is a strength of Einkbro.)

What I'll find over the course of a session is that _occasionally_ the touch location will "creep up" the page.  Since outlines are typically off, this is a hidden behaviour.  I'm not even certain that the movement occurs under user direction.  I do frequently drag-scroll the page, this should _not_ move hidden controls silently.

Suggested changes:

- Highlight the touch areas when they are being dragged.  I suggest _both_ a border _and_ a _background shading_, preferably in contrasting colours.  Black and white would make for maximum viewability given limited colour palettes of e-ink devices.  Mine offers 16 greyscale shades, I'm not sure what is typical.  A 30% / 60% grey might be another option.

- Provide "floating touch area" as a specific alternative.

- Reset the specified location when re-selecting a specific option.  One of my frustrations has been that toggling between two options (e.g., "left" and "bottom") does _not_ restore the touch area position to the bottom of the screen.  A full browser quit is required.

- Highlight the touch area for a moment when it is selected to scroll the page.

- Provide a "floating touch area" as a seperate feature, independent of "left", "bottom", "middle", and "right".

Thanks.

**Comment by plateaukao** [comment]
I think I will disable the moving touch area feature when it's not displayed but turned on. :)

**Comment by dredmorbius** [comment]
Thanks, that would work for me.

**Comment by plateaukao** [comment]
https://github.com/plateaukao/browser/commit/5326c9015f880cf109c1b119c24426f624d615a6

Will be included in next release. :)

**Comment by dredmorbius** [comment]
I've finally installed the release.

Just a note:  I'd delayed install as I had multiple tabs open (as usual) and was concerned about state loss.  Turns out that the tabs _were_ retained, which is useful.  This even in incognito mode.

I'd saved the set off to bookmarks in a dated session folder.  Which ... is also tedious.  No multi-select option to save a batch at once, requiring multi-tap process for each individual tab.

If there's a way to avoid that, I'd like to know.  If not, I'm thinking of another request.

**Comment by plateaukao** [comment]
@dredmorbius Now that lazy loading of multiple tabs is done, I'll consider to add `save session` feature in the future (near future, or far future :). In this way, it should be possible to manually save current opened tabs information in one click, and give it a specific name.

**Comment by dredmorbius** [comment]
@plateaukao I'll attempt to wait patiently for that 😸
