### ISSUE TITLE
This might not  be issue. Need to set Landscape .

### ISSUE THREAD

**Issue by yxxone** [plateaukao/browser#13]
My device might not be able to turn to landscape automatically. So I wonder a setting button would be helpful.

**Comment by plateaukao** [comment]
Hi, @yxxone 

May I know what device you are using? Normally, if you can turn on system auto rotation feature, EinkBro should be able to rotate accordingly. If not, that means your device may not have g-sensor to auto rotate, you have to change system setting to rotate EinkBro app.

**Comment by yxxone** [comment]
I am using MoAn inkpad x which is cheap and might be manufactured without gravity sensor. What make the issue worse is the system does not provide a switch.

**Comment by plateaukao** [comment]
@yxxone will be supported in next version.

**Comment by plateaukao** [comment]
@yxxone  supported in v8.8.0.  https://github.com/plateaukao/browser/releases/tag/v8.8.0
