### ISSUE TITLE
How to switch UI language?

### ISSUE THREAD

**Issue by dyxang** [plateaukao/browser#135]
It seems that there is no separate option to switch languages in the settings.

**Comment by plateaukao** [comment]
@dyxang 
You could change device system language to achieve that. If not, that may indicate that specific language translation is not available.

**Comment by dredmorbius** [comment]
@dyxang I can confirm that setting my device language changes the EinkBro UI language localisation as expected.

You'll need to toggle / set language through the Android system settings (or equivalent for your device / ROM).

From English to German in my case.

**Comment by dredmorbius** [comment]
@plateaukao NB:  EinkBro _did_ crash when I switched back to it after toggling system language.

No session loss, and this is likely not a frequent action.  Still might want to look into that though.

**Comment by Dricc123** [comment]
I installed Einkbro on my Android smartphone that has no Google Services on it (it's a fork of Lineage Android, named Iodé) and have the UI language in an asian language, although my device is set to english...

**Comment by plateaukao** [comment]
there's an issue in latest release. A new version to fix it will soon be released.
