### ISSUE TITLE
Navigation bar DDG bang searches w/ a URL don't work properly

### ISSUE THREAD

**Issue by dredmorbius** [plateaukao/browser#137]
I have DuckDuckGo selected as my primary search engine.

DuckDuckGo offers numerous "[bang searches](https://duckduckgo.com/bang?q=)" for rapidly searching or referencing various sites.  Some of these will take a URL itself, such as the Internet Archive's Wayback Machine (!wayback) or Archive Today (!ais).

For example:

```
!wayback https://github.com/plateaukao/browser/
```

This will show any saved versions of the plateakau/brower GitHub project page.

When a webpage is _already loaded_ (e.g., not in a blank / empty tab), the bang portion of the entry isn't recognised.  Typically either the already-loaded page reloads or the URL given as an argument to the bang search is opened directly.

My present workaround is to first _copy_ the URL, then enter the bang _alone_ and submit that, then paste the URL into the resolved site or service.  This is slower and more error prone than directly entering the bang query.

Multi-part bang-searchs from a _blank_ tab or page seem to work properly best as I can tell.

I may also have seen other issues with URLs having multiple whitespace-delimited entries, though I'm uncertain of this.  I'll update this issue if I happen to notice any in particular.

Expected behaviour:  Entering a multi-part bang query in the navigation bar behaves just as it would if entered on the DuckDuckGo web search page itself (https://duckduckgo.com/).  The query is submitted and completed in one step.

**Comment by dredmorbius** [comment]
@plateaukao I'm not grasping how that might be used or useful.  Could you describe intended use or examples?

It certainly breaks things, and might best be disabled.  

This is _not_ how most browsers function presently (Chrome, Firefox, Safari, w3m, off the top of my head).  Not that I'm a fan of much present browser design, but this particular interface has been useful 😺 

Thanks.

**Comment by plateaukao** [comment]
For example, the shared text I usually got from other apps are like below:
```[卡娜赫拉的小動物 新生活貼圖] https://line.me/S/sticker/14698/?lang=zh-Hant&utm_source=gnsh_stickerDetail```

It's troublesome to manually remove the prefix descriptions. And this feature is requested by other users. That's why I added before.

Yes, you're right; the default behavior should be respecting what user pasted or inputted. If they want some different behavior, they configure the options.  (However, I doubt anyone would know there exists such option though)

**Comment by dredmorbius** [comment]
That does seem like the simplest fix.  Should work for me.

Thanks again.

**Comment by plateaukao** [comment]
fixed in https://github.com/plateaukao/browser/releases/tag/v9.3.0
