### ISSUE TITLE
Feature Request: extra Font size setting 110%

### ISSUE THREAD

**Issue by artelse** [plateaukao/browser#143]
Title says it already, but would love to have a less drastic increase of the font size. On my small screen Hisense A5 phone, 110% would be a good step increase.
Thanks, great browser!

**Comment by plateaukao** [comment]
will check how to do so.

**Comment by plateaukao** [comment]
added in https://github.com/plateaukao/browser/commit/04fad68b53169d1d3b22eccc51f1763f8970dacd
![image](https://user-images.githubusercontent.com/4084738/178050021-325a3dee-14b9-4e6f-a1b5-729373019409.png)

**Comment by artelse** [comment]
Cool, you're fast! F-droid lags latest releases of EinkBro. Will wait till this update appears on GH. Thanks again :)
