### ISSUE TITLE
Some pages Not Found , epub book

### ISSUE THREAD

**Issue by islam2hamy** [plateaukao/browser#145]
https://old.shamela.ws/epubs/000/42.epub

Ex. : from page 14 to 27

**Comment by plateaukao** [comment]
Hi, @islam2hamy 
Thanks for reporting this issue. However, the epub reader support in EinkBro is very very basic. It's intended to be able to quickly read what's saved by EinkBro; but not as a full-fledge ebook reader. So, for issues related to open epub file other than saved by EinkBro, I may not look into the details.
