### ISSUE TITLE
Request about forms data

### ISSUE THREAD

**Issue by islam2hamy** [plateaukao/browser#19]
Can you please add ability not to save forms data

Thank you

**Comment by plateaukao** [comment]
In this App, I didn't do anything to save forms data. Maybe it's supported by your phone system?

Still, you can long press 3 dot button, and turn off cookies when you try to send forms data. Maybe that would help.

**Comment by islam2hamy** [comment]
I cant delete saved data to test that

**Comment by plateaukao** [comment]
You can uninstall the app, and re-install again. :)
If the data is still there, then it's not saved by EinkBro.

**Comment by islam2hamy** [comment]
It is the app :)

**Comment by plateaukao** [comment]
could you provide the Android OS version, and on what web site the form data will be saved? I will try if I can reproduce the issue in Emulator.

**Comment by islam2hamy** [comment]
Miui 11.0.2
Any site , try https://github.com/

**Comment by islam2hamy** [comment]
https://developer.android.com/guide/topics/text/autofill

**Comment by islam2hamy** [comment]
https://support.mozilla.org/bm/questions/813403

**Comment by plateaukao** [comment]
Thanks for the links. I found something helpful: https://developer.android.com/reference/android/webkit/WebSettings#setSaveFormData(boolean)

But seems that only works for devices below Android SDK 26 (Android 8.0); I might not add the option, since that's not the main target versions for this app.

**Comment by islam2hamy** [comment]
https://github.com/scoute-dich/browser/commit/e8cb3a860f3baf955324ea078f8153efde583468

**Comment by islam2hamy** [comment]
Can it be done here also ?
Please

**Comment by islam2hamy** [comment]
https://github.com/scoute-dich/browser/pull/557/commits/49255f3d127de16a685ed0fd3c577b029b585801

**Comment by islam2hamy** [comment]
Can you please add it ?

**Comment by plateaukao** [comment]
Added a new option in Setting > Start control.
Not sure if it works though. For me, it always not fill anything automatically for me.

**Comment by islam2hamy** [comment]
Any apk to test ?

**Comment by plateaukao** [comment]
You could download the nightly build on GitHub main page,  unzip the file and install it.

**Comment by islam2hamy** [comment]
LOL , now it is work
Thank you
