### ISSUE TITLE
Bin from source with mic

### ISSUE THREAD

**Issue by xyzsco** [plateaukao/browser#26]
Hi,

I wanted to use for google voice in browser temporarily i get my voice line running again. 

Where do I enable mic permissions in the source code?

Thanks!

- Jeremy

**Comment by plateaukao** [comment]
Hi, you can try to show permission dialog just before you want to use google voice.

**Comment by xyzsco** [comment]
The only inherit permissions are network and location. So, I doubt that
will help...

**Comment by plateaukao** [comment]
I am not sure what you mean by "inherit". You can take a look at https://github.com/plateaukao/browser/blob/main/app/src/main/java/de/baumann/browser/unit/HelperUnit.kt#L53 about how to get storage permissions from user.

**Comment by xyzsco** [comment]
Storage has nothing to do with it,

Strictly microphone permissions.

Google voice requires this to talk on the phone with someone.

**Comment by plateaukao** [comment]
I mean you can refer to how the permission request is implemented, and write  similar codes for what you want for microphone permission. I know storage permission has nothing to do with your feature.

**Comment by xyzsco** [comment]
Ok, thanks for the clarification.
