### ISSUE TITLE
[Feature Request] Add custom rules for Ad Blocker

### ISSUE THREAD

**Issue by ZZYSonny** [plateaukao/browser#29]
When I am browsing websites using eink Bro, I sometimes want to change the website layout to better fit the screen. And the easiest way is probably hiding some element with the adblocker. It will be great if we can add custom rules for adblocker in eink Bro.

The way can be a text box. User can test rules on their pc and copy it here.

Or maybe it is possible to expose the setting page of Ad Blocker?

![Screenshot_2021-07-01-14-59-32-01.jpg](https://user-images.githubusercontent.com/28442838/124080439-f5d35600-da7c-11eb-80e8-95f549fc4c59.jpg)

**Comment by plateaukao** [comment]
Hi, @ZZYSonny  pull request is welcomed. If you can send me a PR, I will look into whether it can be fit into EinkBro app. Thanks.

**Comment by ZZYSonny** [comment]
Hi recently I ported to scrolling buttons (the soul of eink bro) to html & javascript. Now I am using kiwi browser, which is chrome browser on android but allows extension, with tampermonkey to load my script and ublock for adblocking. See my script here. https://greasyfork.org/zh-CN/scripts/431048-pageup-and-pagedown-button.

From what I see, ad blocking or more recent chromium version (whereas eink bro uses system webview) may improve performance. Some sites eink bro is struggling to load can load in reasonable time on kiwi.

**Comment by plateaukao** [comment]
Hi @ZZYSonny Thank you for the information. I'll take a look at it. Also, EinkBro imrpoved web loading performance. You can try v8.14.0 and feel the difference.

**Comment by plateaukao** [comment]
A simple way of adding Ad blocking domain: just long click on Ad image, it will show an option to add Adblock url. modify the url and save it.
