### ISSUE TITLE
Can't scroll to see full page name in history view

### ISSUE THREAD

**Issue by AJolly** [plateaukao/browser#336]
I can't scroll to see the full page name in history view, which is exasperated by it splitting each line into two.

![IMG20240213110935](https://github.com/plateaukao/einkbro/assets/91493/715bd14a-5b83-4e09-873c-084a4e79d495)

It's mostly a problem when I'm trying to figure out where I left off reading a book, and the chapter numbers are cut off. 

I was expecting to be able to use my finger to scroll a page name, or have it auto scroll.

**Comment by plateaukao** [comment]
That sounds like a good idea. 
However, scrolling is not a preferred behavior on Eink devices, so I made the ellipsize in the middle of text, so that you should be able to see the end part of the title.

**Comment by plateaukao** [comment]
Also, if you still can't read the info you need in the title, you can long click on each history item, with a popup to show its full content.

**Comment by AJolly** [comment]
Sounds great! 
The same thing applies to the tab switcher but it's probably much less important there.

![IMG20240214111626](https://github.com/plateaukao/einkbro/assets/91493/f6c9662a-1407-49db-bf50-eaa080f8a684)
