### ISSUE TITLE
EinkBro uses the old link, even though the current page shows the page in the new link

### ISSUE THREAD

**Issue by searene** [plateaukao/browser#35]
First of all, I want to thank you for creating such an amazing app. It's really helpful, I appreciate your efforts!

However, I encountered a problem when using this app. Here are the steps to reproduce it:
1. Open `www.google.com` using EinkBro
2. Search for `eink`
3. Open any link in the search result, let's say "E Ink - Wikipedia"

At this point, the address bar still shows the current page is "eink - Google Search", although it's not. The link shown in "Share link" and "Open link with..." is also the link to "eink - Google Search", instead of the correct one("E Ink Wikipedia"). What's more, the opened "E Ink - Wikipedia" page's font is weird, it's different from the page used in normal pages. The page cannot be scrolled using the touch area, either.

This problem doesn't occur when I use "DuckDuckGo" to search, that's weird.

**Comment by plateaukao** [comment]
it works on my device. Could you give more details about your device info? And, if possible, could you record a video for this issue?  Thanks.

**Comment by searene** [comment]
@plateaukao 

Thanks for the reply. My device is Boox NotePro, the Android version is 6.0.1. If you need any other info please let me know.

Here is the recorded video, notice that after I entered the Wikipedia page:
1. The touch area doesn't work
2. The font turned bold(Which is not set by me, and I cannot change it by changing EinkBro's settings).
3. The address bar still shows the current page is "eink - Google search".
4. The link shared is still "eink - Google search".

https://user-images.githubusercontent.com/3351317/127183601-4e226b34-c401-4009-871a-dd82c6867413.mp4

**Comment by plateaukao** [comment]
Hi, @searene Thanks for providing more info. It seems the attached file is audio instead of video?

**Comment by searene** [comment]
> Hi, @searene Thanks for providing more info. It seems the attached file is audio instead of video?

That's weird, it cannot play, but it worked just fine after downloading it. Anyway, I'm uploading this video to YouTube. I will tell you when it's done.

**Comment by searene** [comment]
@plateaukao Hi, this is the YouTube link: https://www.youtube.com/watch?v=koE9Dab0Npo

**Comment by plateaukao** [comment]
Hi, @searene  I tried on Note 3, it works well. 
Also, I tried the same behavior on Emulator with Android version 5, and it works well too. I guess that's because Onyx has some modifications to the WebView implementations that changed the behavior of the web browsing. Not sure if that's the root cause.

**Comment by searene** [comment]
> Hi, @searene I tried on Note 3, it works well.
> Also, I tried the same behavior on Emulator with Android version 5, and it works well too. I guess that's because Onyx has some modifications to the WebView implementations that changed the behavior of the web browsing. Not sure if that's the root cause.

Maybe that's the cause, if so, I can do nothing about it. Thanks anyway :)
