### ISSUE TITLE
Force close on Koudaiyue 1st gen.

### ISSUE THREAD

**Issue by Xuyiyang23333** [plateaukao/browser#36]
When I open the app, a window pops up saying “EinkBro has stopped”.
CPU: Unisoc sc9832e
What should I do?

**Comment by Xuyiyang23333** [comment]
FOSS browser has the same problem, maybe I need to ask the question somewhere else...

**Comment by plateaukao** [comment]
Hi, Could you provide what Android OS Koudaiyue is using, and what EinkBro app you are using? Also, it would be helpful if  you can provide the crash logs, since I don't have Koudaiyue device at hand; I may not be able to reproduce the issue.

**Comment by Xuyiyang23333** [comment]
> Hi, Could you provide what Android OS Koudaiyue is using, and what EinkBro app version you are using? Also, it would be helpful if you can provide the crash logs, since I don't have Koudaiyue device at hand; I may not be able to reproduce the issue.

Thanks for your reply, I hope this helps.
Android OS: Android 8.1 Go
<details>
  <summary>crash.log</summary>
07-28 13:30:18.827 19618 19618 E AndroidRuntime: FATAL EXCEPTION: main
07-28 13:30:18.827 19618 19618 E AndroidRuntime: Process: info.plateaukao.einkbro, PID: 19618
07-28 13:30:18.827 19618 19618 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "void android.webkit.WebSettings.setSafeBrowsingEnabled(boolean)"
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at de.baumann.browser.view.j.j(Unknown Source:30)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at de.baumann.browser.view.j.<init>(Unknown Source:134)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at de.baumann.browser.activity.BrowserActivity.x0(Unknown Source:7)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at de.baumann.browser.activity.BrowserActivity.y0(Unknown Source:28)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at de.baumann.browser.activity.BrowserActivity.C0(Unknown Source:173)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at de.baumann.browser.activity.BrowserActivity.onCreate(Unknown Source:484)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7064)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7055)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1217)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2812)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2955)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(Unknown Source:0)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6747)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:449)
07-28 13:30:18.827 19618 19618 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
</details>

**Comment by plateaukao** [comment]
strange. 
About setSafeBrowsingEnabled it's already limited to be set after Android SDK 26 in codes:
```kotlin
        if (Build.VERSION.SDK_INT >= 26) {
            settings.safeBrowsingEnabled = true
        }

```

I will move it to other place to see if it works.

**Comment by plateaukao** [comment]
Please try this version: https://github.com/plateaukao/browser/releases/tag/v8.12.1
