### ISSUE TITLE
When downloading a .Epub it always is the filename.epub" instead of just .epub

### ISSUE THREAD

**Issue by rvcjew** [plateaukao/browser#37]
Version 8.11.0:

When downloading .epub files from certain sites that don't provide the name of the file in the url it self it will download the file fine but always add an " to the end of the extension.

To recreate:

Downloading:
https://filesamples.com/samples/ebook/epub/famouspaintings.epub

Gives the file as the correct extension name

Downloading: https://www.fimfiction.net/story/download/41596/epub (as an example of a site that does this) 

Gives an " at the end.

This is on a note 9 8.1 os as well as an 8.1 os eReader. So device independent.

Also would be nice if long press showed the link you were selecting above the save options but that is a feature request.

**Comment by plateaukao** [comment]
Hi, @rvcjew  I am not sure why sometimes the filename is not correctly recognized by EinkBro App. It has logic to identify filename in original implementation, but seems not working well in some circumstances. I will create a dialog before really downloading file, so that user can decide whether to change the file name if he wants too.

As for long pressing showing the link, I will consider this feature in the future. Thanks for the advice.

**Comment by rvcjew** [comment]
Yeah I figured a simple prompt to quickly rename it would be good. For my
own needs I only need to download books every now and then and the rest of
the browser is great on my InkPalm 5. It wasn't much of an issue but old
files had no " so moon plus did not have the same database for the new
named file.

I did notice that when doing save as on the epub test site it knows its a
epub but as you said on the fimfiction site it thinks it is a .bin file.

Thanks for the support.
Malcolm

**Comment by plateaukao** [comment]
Hi, @rvcjew 
please try version 8.12.0: https://github.com/plateaukao/browser/releases/tag/v8.12.0

**Comment by rvcjew** [comment]
Hi Daniel:

The new one let's me change the name and I hit ok. Then it says starting
download (as a toast message) but never downloads anything or even part of
anything. It doesn't put a single file in my downloads folder or any other
folder on internal storage. It also never then says it's done do you want
to view the file manager.

This is on a note 9, 8.1 os for testing.

Thanks.

**Comment by plateaukao** [comment]
@rvcjew   hm... strange to hear that it did not work in the beginning.
Fortunately, reboot solves everything. :D
