### ISSUE TITLE
Blank ad banner(?) appears at the bottom of the screen and obscures content

### ISSUE THREAD

**Issue by asampal** [plateaukao/browser#4]
With version 8.7.2 on an Onyx Boox Max 3, I see a blank (maybe it's intended to display an ad) rectangle obscuring some of the page right above the toolbar in the browser. There is an "X" at the top right of this rectangle as if to allow closing it, but it doesn't react to touch or pen input.

![IMG_20210421_212401~2](https://user-images.githubusercontent.com/281639/115642129-e95ab080-a309-11eb-91af-606c4bd09db3.jpg)

**Comment by plateaukao** [comment]
I think the ad area is designed by the web page. I did not add any ad in EinkBro. Did you download the app from here or othwr place?

**Comment by asampal** [comment]
You're right about it being that web page. I downloaded from here.

I notice that there is an adblocker built in - is it a known one like uBlock Origin?

**Comment by plateaukao** [comment]
I guess so. You can try to turn it off and all the ads will come out again. It checks whether images are from some ad agency domains. If so, it does not load them intovwebpage.
