### ISSUE TITLE
The requirements of CSInTraditionalChineseCalligraphy,Thank you！！

### ISSUE THREAD

**Issue by smallwhite123298** [plateaukao/browser#44]
Hello,I am interested at your project called CSInTraditionalChineseCalligraphy in Github,but I can't run it.can you give me its requirements or some published papers about it?Thank you!!

**Comment by plateaukao** [comment]
@smallwhite123298  it's forked from others long time ago, so I have no idea too. :)

**Comment by smallwhite123298** [comment]
> @smallwhite123298 it's forked from others long time ago, so I have no idea too. :)
OK, thank you very much, but I'm doing research in related directions. I'm anxious to make some improvements in this project. If you can, can you provide me with some relevant information about this project and I can pay some remuneration.

**Comment by plateaukao** [comment]
As I remember, I just forked and didn't do any study yet. :p
