### ISSUE TITLE
FR: Volume buttons behavior option

### ISSUE THREAD

**Issue by Buntbart** [plateaukao/browser#5]
Thank you for EinkBro!

Please consider to make the behavior of the hardware buttons optional in the app settings. Currently it's not possible to regulate the audio volume of media sites because the volume buttons are used for scrolling.

**Comment by plateaukao** [comment]
okay! I'll add it in next version

**Comment by plateaukao** [comment]
@Buntbart  it's added in v8.7.3 in quick toggle dialog (by long pressing 3-dot icon). Please have a try.

**Comment by Buntbart** [comment]
Great, thank you for your efforts! I'm looking forward to 8.7.3 to be released on F-Droid.
