### ISSUE TITLE
"Save as pdf" does not work on Boox Nova 2

### ISSUE THREAD

**Issue by robertocarta** [plateaukao/browser#55]
As per title, tapping doesn't do anything - no errors returned either. "Save epub" works perfectly.

P.s. A wholehearted thanks for this project, it was badly needed and it's massively changed my routine.

**Comment by plateaukao** [comment]
@robertocarta Thanks for reporting this issue. I'll check what went wrong on my Note3 today. Glad that you like this project. :)

**Comment by plateaukao** [comment]
Hi, @robertocarta
I tried on my Note3 and it works. I am not sure whether BOOX Nova 2 removed the printer support.

**Comment by plateaukao** [comment]
should be device issue.
