### ISSUE TITLE
Hard to go back to baidu.com after clicking search results

### ISSUE THREAD

**Issue by xgdgsc** [plateaukao/browser#56]
When I search something on baidu.com, like search "some" and click on the baidu baike link (https://baike.baidu.com/item/some/7777625?fr=aladdin). And press return key to go back. It hardly succeeds. Usually it just goes to the current page top. Other browser like Firefox doesn' t have this issue.

**Comment by plateaukao** [comment]
There are some url redirection going on in baidu.com. It's hard to handle this kind of url handling done by website. 

In this scenario, you can long press < on the toolbar, it will show recent visited url. And then you can click on the previous search.

**Comment by chenjunyi1990** [comment]
这个原因，主要在于电脑端的浏览器和安卓端浏览器设计上的不同。电脑端很容易返回，安卓端就需要点击切换一下页面标签才可以。

**Comment by plateaukao** [comment]
看起來百度修了它的網頁。目前我測試是可以的。

**Comment by plateaukao** [comment]
@xgdgsc 
請參考 #260 ，這問題應該是解了。會在版本 10.9.0 中
