### ISSUE TITLE
Support Android SDK level 19?

### ISSUE THREAD

**Issue by lclrc** [plateaukao/browser#57]
Hello, Is there any chance to support SDK19 again?

**Comment by plateaukao** [comment]
I tried several months ago, but SDK 19 is way to far from current version, too much to change to make it compilable. In the end, I gave up. If you find a way to make it work for sdk 19 without much changing the codes, please let me know. I would love to support it in this case.

**Comment by lclrc** [comment]
> too much to change to make it compilable

Sorry for hear that. Anyway, thanks for your work!
