### ISSUE TITLE
[Reference] Translate webpage using Google Translate API

### ISSUE THREAD

**Issue by winstonma** [plateaukao/browser#58]
Currently I installed [Translate Web Pages](https://addons.mozilla.org/en-US/firefox/addon/traduzir-paginas-web/) on my Firefox. When I ask for a translate page they would just replace the article content with the translated word and without reloading the whole page. As the translate is much faster (no need to reload the whole page), I went to their [Github](https://github.com/FilipePS/Traduzir-paginas-web) and take a look.

I guess they are extracting the content inside webpage, do translation, and replace the content back into the webpage ([translationService.js](https://github.com/FilipePS/Traduzir-paginas-web/blob/master/background/translationService.js) should be the extraction and translation part).

I am currently happy with the EinkBro translate. This is just a reference.

**Comment by plateaukao** [comment]
Cool! Thanks for the information. I will try to install it on Firefox and see how it works. :D

**Comment by plateaukao** [comment]
@winstonma 
A better way is provided in https://github.com/plateaukao/browser/releases/tag/v8.25.0
Please try the Google in Place option in Translate configuration dialog. :)

**Comment by winstonma** [comment]
Thanks. I downloaded v8.25.0 and it is much smoother. It is very obvious when I am running the new translation on my old Boox Nova.

Thanks a lot.
