### ISSUE TITLE
Request: Ability to hide button when in full screen mode

### ISSUE THREAD

**Issue by jcolesy** [plateaukao/browser#59]
Thank you for a great piece of software! It would be great if you could hide the button in the bottom right corner when in full screen mode -  I think it would help with immersion when reading long form text.

**Comment by plateaukao** [comment]
@jcolesy Good suggestion! Added in next version. (You can configure it in Settings -> UI & Behavior -> fab Position. And press back key to show the toolbar again). Here's the commit: https://github.com/plateaukao/browser/commit/50a897e298780265a97537577e128af25e566cc0
