### ISSUE TITLE
Using xhtml instead of html when converting to ePub

### ISSUE THREAD

**Issue by wasu-code** [plateaukao/browser#62]
Hi. As far as I know ePub should consist of .xhtml files instead of .html. For that reason all tags should have closing tags. So instead of `<br>` there should be `<br />`. The same goes to `<hr/>` tag.  
It should also have something like this:
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
```
at the beggining.  

Although most ebook readers (like Moon+ Reader) deal with it without any problems I came across some that wasn't able to read the ebook properly when `xmlns="http://www.w3.org/1999/xhtml` in not specified at the beggining of file. (the example of one that had problems is "Reasily")

**Comment by plateaukao** [comment]
Thanks for pointing this out.

I tried to fix some of the errors; however, as you said, Reasily will also check whether tags are closing tags. There are too much modification needed for EinkBro App to support Reasily's strictness on the formats.

So, I prefer not  modifying anything at all, and ask users to use a more error-tolerant ebook reader.

If you find a perfect conversion code snippet that I can apply to existing html string and make it more epub compatible, I would love to have a try.

**Comment by kasperpeulen** [comment]
@plateaukao I think if you don't close a hr tag, it is displayed as a border around the page in koreader:

![Reader_2022-08-20_103743](https://user-images.githubusercontent.com/1035299/185737969-3276a043-5f02-4b2d-acee-80104cef5b2f.png)

I would love it if einkbro would convert all the <hr> and <br> to self closing tags.

**Comment by plateaukao** [comment]
@kasperpeulen 
Thanks for pointing out the issue of hr tag. after adding close / to it, in KoReader, it does hide the border. I will fix this first.

As for adding all tags with self closing /, now I don't know an easier to do so. When I do, I will do fix this part too.
