### ISSUE TITLE
Frozen app / force stop doesn't help.

### ISSUE THREAD

**Issue by gety9** [plateaukao/browser#64]
Einkbro suddenly froze (first time it happens), and now i can't kill it. 
Force stop does not help, neither restarting the device. 

When i try to open app it opens from same frozen page and after some time says
"Einkbro doesn't respond
- stop process  
- wait" 
Neither of which helps.

I think it's connected to "save pages / tabs" setting, now Einkbro saves this frozen state.

I can reinstall the app and it should fix it, but maybe while it still frozen i can provide log or smng which will be helpful to you? (though i am not developer)

Here is screenshot as start:
![Screenshot_20211227-164357](https://user-images.githubusercontent.com/16415882/147509374-16b128b8-0236-487f-998d-a74800a4a76b.png)

**Comment by gety9** [comment]
Update:
Unfroze, probably after 15-20 min... :)

I can close the issue or keep it open as possible improvement not to "save pages / tabs" for non responsive pages.

**Comment by plateaukao** [comment]
@gety9 Next time it happens, you can long press on the icon on Home, and try to launch bookmark page instead to see if it helps. I sometimes encounter it but not sure why it happens (it may be related to specific web pages). So myself seldom use saving tabs feature. It also slows down loading time when launching the app, since it will create multiple webview instance.

**Comment by gety9** [comment]
@plateaukao 

> Next time it happens, you can long press on the icon on Home, and try to launch bookmark page instead to see if it helps.

i have note air 2 and have only power button, no other buttons.
Do you have other ideas how to unfreeze?
I tried "Clear cache" - no help,
If i try "Clear storage" - will Einkbro's setting be lost?

> I sometimes encounter it but not sure why it happens (it may be related to specific web pages)

i think i find the page that freeze Einkbro for me:
google "emacs init.el detect android"
and choose "init.el / coldnew.github.io/coldnew-emacs/init.el.html" result
it should freeze (opens fine on FF)
p.s. i am not 100% sure, cause i can't retest - i am in frozen state now, but that's the page
which froze me this time.

> So myself seldom use saving tabs feature. It also slows down loading time when launching the app, since it will create multiple webview instance.

i find save tab feature useful cause i often browse for research purposes and it can take 2-3 days for me to arrive to conclusion (when i can close the tabs)
Do you think it possible to improve save tab feature no to save unresponsive tabs? Or to kill the automatically (let's say if tab does not response for 2-3 min or smng)

**Comment by plateaukao** [comment]
@gety9  
* Clear cache only clears some images and cached htmls, it does not clear saved tabs.
* Yes, if you clear storage, the einkbro settings will be all gone. You can always save your bookmark list first in Settings > Backup, whenever you want to do so.

I tried following the same behavior on my emulator, it does not hang the device.
<img width="557" alt="image" src="https://user-images.githubusercontent.com/4084738/147579296-da36c5d8-734d-438c-8fb5-895b5a54bd5c.png">


* on ONYX device, you can define gestures to swipe from the bottom of the device, and assign them actions like Eink Setting, or Go Back, or Go Home screen, etc. 

* In codes, it's hard to define what's unresponsive. When it froze, can you still press the tab button and show the tab list?

* I will try the same behavior on my Note 3 and see if it happens

**Comment by plateaukao** [comment]
@gety9 I think I could reproduce it.. please try turning off Bold font feature next time. I am not sure why, maybe something conflict between the bold font css style and ONYX's default injected css.

**Comment by plateaukao** [comment]
@gety9 I tried the url with built-in NeoBrowser, it hangs as well. It's a problem either on the website itself, or the webview comes with ONYX devices. There's nothing I can do.

Also, the reason why firefox works may be because it's not using Chrome's webview component. It has its own rendering engine.

And I checked the inti.el.html. It looks like it tries to hook geolocation or something which I don't know what's that for or any related to the actual html content. Maybe it's just mal function of the javascript code, and firefox has better error handling in this case.
<img width="772" alt="image" src="https://user-images.githubusercontent.com/4084738/147582199-8af29c25-d0b3-4391-a365-31a0f2ae2127.png">

**Comment by gety9** [comment]
@plateaukao 

> In codes, it's hard to define what's unresponsive. When it froze, can you still press the tab button and show the tab list?

nope, can't do anything at all aside from pressing navigation ball.

> Also, the reason why firefox works may be because it's not using Chrome's webview component. It has its own rendering engine.

I checked it on my desktop, not tablet, so it my freeze too. I should've clarified it in previous comment, sorry.

**Comment by gety9** [comment]
@plateaukao 
this time it didn't unfreeze so i had to reinstall the app and it solved it.

Not sure if it's possible but please consider making unresponsive pages ignored for "save tabs" feature or auto killed after X minutes.

I would like to continue using save tabs feature (without risking another unplanned reinstall)

**Comment by plateaukao** [comment]
I'll consider add a shortcut to open EinkBro without loading saved tab lists. This might mitigate the issues you encountered. :)

**Comment by plateaukao** [comment]
@gety9 
Added a home shortcut (long press icon on EinkBro App, and you can click on Home item) to launch only home page. https://github.com/plateaukao/browser/releases/tag/v8.25.0

**Comment by gety9** [comment]
@plateaukao 
could you please clarify the steps?

When i am in apps long press brings 
- uninstall
- manage
- optimize
- add to group

**Comment by plateaukao** [comment]
Well, it looks like BOOX built-in interface does not support shortcut feature... too bad.

 ![Screenshot_20220104-004743.png](https://user-images.githubusercontent.com/4084738/147956874-855bad9a-9cd8-4904-97af-36c73d5f36c5.png)

**Comment by gety9** [comment]
@plateaukao 
to enable it do i need to install custom mod or smng (or launcher) - i am new to android :)

**Comment by plateaukao** [comment]
I just tried. it seems the whole system does not support shortcuts, so even if I install 3rd party launcher, it does not show the options.
