### ISSUE TITLE
[Feature Request] Translater System

### ISSUE THREAD

**Issue by bakinazik** [plateaukao/browser#65]
Can you take a look at the translation system of the [Via browser](https://play.google.com/store/apps/details?id=mark.via.gp)? They adapted the system, with which we can add [translations to our site ](https://www.w3schools.com/howto/howto_google_translate.asp)with a single javascript code, to a mobile view. I don't know exactly how it works, but it's super useful. 
I wish we could see this feature in this browser..

**Comment by bakinazik** [comment]
It can be used very comfortably because it works much faster than the standard translation system and causes less ram consumption.

**Comment by plateaukao** [comment]
Hi, @bakinazik 
Thanks for providing the information, I will take a look into it. In the meanwhile, EinkBro already supports Google Translation in another view. You can access it from toolbar configuration (in Menu, second row, right most icon). After adding the Translate button in toolbar, you can long press to select GOOGLE_URL, and then go the url you want to translate, and press the TRANSLATE button again. it will show a split screen with full translated web content.

**Comment by plateaukao** [comment]
@bakinazik 
I tried to add similar feature in Translate configuration with label "Google in Place" in commit 921adbe61063dedcf0e79b465ca8e2879d11b9ac . When it's released, you can have a try.

**Comment by plateaukao** [comment]
released in https://github.com/plateaukao/browser/releases/tag/v8.25.0
