### ISSUE TITLE
Hardware Recommendations?

### ISSUE THREAD

**Issue by guettli** [plateaukao/browser#66]
I am looking for a e-ink device for web browsing.

Do you have any hardware recommendations?

**Comment by gety9** [comment]
@guettli 
I recommend you check my deep guide on youtube,
it helped me tremendously with my first e-ink tablet purchase.

tldr: Onyx boox devices are now best option (good price, open platform), with boox note and boox note air most popular lines.

**Comment by plateaukao** [comment]
@guettli 
Latest Eink devices from Onyx would be a good choice, although the device battery can not last for several years long, but its performance of web browsing is the best among mainstream Eink devices.

**Comment by chenjunyi1990** [comment]
> 

Recommend you to use the eink screen monitor，In this way, it can be used on a computer，Become a productivity tool。You can install einkbro on the Android emulator and use it with a  eink monitor,like  boox mira,or paperlike。
eink is not suitable for scrolling, only suitable for page turning without page turning animation effect.

**Comment by guettli** [comment]
@chenjunyi1990 my use case is reading in the evening (sitting on the sofa) and playing chess. A computer is too big for me. A tablet like device is what I am looking for.

**Comment by chenjunyi1990** [comment]
> 

eink pad is more suitable when reading on sofa,like  boox note 3,boox note x,boox max lumi,dasung 103，……many to choose
