### ISSUE TITLE
Transforms any query ending with aaa.bb to url.

### ISSUE THREAD

**Issue by gety9** [plateaukao/browser#67]
Einkbro tries to transform any query ending with aaa.bb to url.

Example:
1 "+" for new tab
2 enter "how to open design.psd" OR "wireless mouse amazon.com", etc

Result
```
Webpage not available
The webpage at https://how%20to%20open%20design.psd/ could not be loaded because:

net::ERR_NAME_NOT_RESOLVED
```

It works fine on neobrowser.

Proposed solution:
If query has " " (space) treat it as search. Cause none of urls on the web have " " in url.

**Comment by plateaukao** [comment]
Another good issue reporting. I will check how I can improve this search keyword / real url check.

**Comment by plateaukao** [comment]
fixed in https://github.com/plateaukao/browser/commit/d78b3f37b933722e9eddb3cb35d96b6bc5b4c659

**Comment by plateaukao** [comment]
released in https://github.com/plateaukao/browser/releases/tag/v8.25.0

**Comment by gety9** [comment]
@plateaukao 
works, thank you.
