### ISSUE TITLE
Using bold setting makes Titles disappear on tab preview.

### ISSUE THREAD

**Issue by gety9** [plateaukao/browser#68]
Tab preview is very useful for navigation, however titles disappear if one uses bold setting.

Non bold setting:
![Screenshot_20211229-105848](https://user-images.githubusercontent.com/16415882/147682150-6532e1bf-3f0b-4310-b916-49b949a30785.png)

Change to bold setting:
![Screenshot_20211229-110042](https://user-images.githubusercontent.com/16415882/147682208-ff685c87-01ec-47f4-bcdc-79c6137dfed2.png)

**Comment by plateaukao** [comment]
wow! it's true! sometimes I found tab preview to be empty strings and didn't know how it happened. Thanks for reporting this issue, I will check what went wrong.

**Comment by plateaukao** [comment]
fixed in https://github.com/plateaukao/browser/commit/d78b3f37b933722e9eddb3cb35d96b6bc5b4c659

**Comment by plateaukao** [comment]
released in https://github.com/plateaukao/browser/releases/tag/v8.25.0

**Comment by gety9** [comment]
@plateaukao 
works, thank you.
