### ISSUE TITLE
Add "new tab" and "search on site" to toolbar setting.

### ISSUE THREAD

**Issue by gety9** [plateaukao/browser#71]
Eink bro has very convenient UX (speed, layout of items, navigation) - Daniel did mazing job! - and i think what can be improved is to add:

- "new tab" (maybe also "new tab in private mode" if it's often used by users)
- "search on site"

to toolbar settings so user can enable them if he wants. 

These are 2 frequent actions that now require 2 taps instead of 1 tap. 

Especially new tab - it's one of the most frequent actions any user does. (and i don't think we need to change tab preview, i don't mind to have "+" on both tool bar default and tab preview activated one - actually i think it's better.)

**Comment by plateaukao** [comment]
both are added. please check https://github.com/plateaukao/browser/releases/tag/v9.3.0
