### ISSUE TITLE
eink显示器boox mira必不可少的工具

### ISSUE THREAD

**Issue by chenjunyi1990** [plateaukao/browser#74]
我使用boox mira这款eink电子墨水屏幕显示器作为护眼屏幕，显示文字类内容。其实大上科技是最早做电子墨水屏幕显示器的，有paperlike。大上科技和文石boox两家的产品都不错。
eink屏幕天生不适合滚动，只适合翻页。einkbro本身是为电子墨水的安卓平板设计，但同理也可以使用在电脑、搭配eink显示器上。
目前我使用安卓模拟器，在PC上使用einkbro，真的是完美。当然，一些浏览器插件也可以实现无动画翻页，如chrome和edge上的reader view（好几款同名的，要注意挑选只有一个可以真正实现无动画翻页），但这些插件在搜索时，或者网页不方便转为阅读模式时，就无法用，所以这时候einkbro就是不可替代的。
感谢开发者！thank you!

**Comment by chenjunyi1990** [comment]
look forward to the win version of this software, which is more convenient to use  einkbro on PC with eink monitor ，like boox mira,paperlike.

**Comment by plateaukao** [comment]
Thank you for your comment. :)
