### ISSUE TITLE
Toolbar formatting issue (title / controls)

### ISSUE THREAD

**Issue by gety9** [plateaukao/browser#77]
Sometimes toolbar formatting breaks and title starts to ocupy all tool bar length making controls not visible:
![Screenshot_20220213-054042](https://user-images.githubusercontent.com/16415882/153749836-6bb72d8f-0d20-46c1-9884-063a9bdf3c55.png)

It possible to scroll toolbar, but then beginning is of title is not visible:
![Screenshot_20220213-054115](https://user-images.githubusercontent.com/16415882/153749890-ca3e22df-056f-4ecb-8ba0-590e0bd5fcb7.png)

If i go to multitasking switcher and close Eink bro, then reopen it, it fixes it:
![Screenshot_20220213-054335](https://user-images.githubusercontent.com/16415882/153749960-62dfe7f6-5908-40ca-8e8e-dc7d13c3c9d6.png)

(I asked about this issue before https://github.com/plateaukao/browser/issues/63 (question 1), but it took time to understand what's going on)

**Comment by gety9** [comment]
@plateaukao 
i use portrait (as screenshots) most of the time, i tested and
-, if browser is in "good state" (screenshot 3) rotating does not break it
-, if browser is in  "bad state" (screenshots 1 and 2) rotating does not fix it

I think rest of icons is more important than title, plus in title itself beginning is most important, so maybe following logic is appropriate:
-, display all rest of icons
-, if there is more space show shortened title

**Comment by plateaukao** [comment]
@gety9 

I refactored how toolbar is built. Now it should work fine for your case. Please have a try: https://github.com/plateaukao/browser/releases/tag/v8.29.2

**Comment by gety9** [comment]
@plateaukao using 8.29.2 for last 3 days, and it seem to solve the issue, never had "bad state" triggered.

Thank you the fix and listening to your users :)
