### ISSUE TITLE
EInkBro gets me locked out of paywall sites

### ISSUE THREAD

**Issue by LKgY** [plateaukao/browser#86]
Hi, 

I downloaded this browser so I could read long articles behind paywalls with my e-ink device, however I have now been locked out of two different paywall while using your browser. What typically happens is that I am prompted to complete a number of captchas only for there to appear a message asking me to contact customer services. 

This issue has _not_ previously presented when using Chrome-based browsers. One site appears to have disabled my subscription entirely, they are not responding to my e-mails. 

Very disappointing!

**Comment by plateaukao** [comment]
please provide what paywall service you use and how did you do to read behind paywalls, and is it legal to do so? . Reporting issues without websiteurl , is hard to investigate why. please re open the ticket with more necessay information.
