### ISSUE TITLE
non-http fallback URLs and deeplinks handling 

### ISSUE THREAD

**Issue by Kita2345** [plateaukao/browser#89]
**Problem** When a `NonHttpAppLink` is intercepted (_intent://_ etc.) and the `fallbackUrl` is used (When no activities are found for the initial `Intent`), then the `fallbackUrl` is loaded as a normal web link.
 
This is problematic if the `fallbackUrl` is a _market://_ link for example, which will fail to load in the `WebView`.

**Solution** If the `fallbackUrl` is a `NonHttpAppLink`, then an `Intent` for that link is created and launched if the initial `Intent` does not resolve any activities.

Visit: https://studio.click.godaddy.com/FVXM/f2c4755d
play store not loaded

**Comment by plateaukao** [comment]
@Kita2345 please check the latest commit or wait for the next formal release. :)

**Comment by plateaukao** [comment]
fixed
