### ISSUE TITLE
Google translate automatically kicking me out of coding tutorial pages. Can't turn off permanently

### ISSUE THREAD

**Issue by GithubUser017** [plateaukao/browser#97]
I'm using dataquest.io to learn python. When e-ink bro detects that the string typed is a language other than english, a google translate bar pops up on the top of the page and kicks me out of the page, loosing the work. It regards each dataquest.io assignment page as a different page, so "turning off translate for this page" does not work. This issue maybe similar to #73 ? Not sure. ** It would be helpful if there was a way to permanently turn off google translate**, to prevent from repeatedly losing all progress. Thanks for great project!

**Comment by plateaukao** [comment]
Thanks for reporting this issue.
I will add an option to enable keyboard shortcuts in next release. So, by default, it won't interfere with your typings.

**Comment by GithubUser017** [comment]
Thanks so much!

**Comment by plateaukao** [comment]
@GithubUser017  https://github.com/plateaukao/browser/releases/tag/v8.31.0

**Comment by GithubUser017** [comment]
seems to be working perfectly! Both on android and Windows 10 with bluestacks seem to run perfectly, thanks!

**Comment by plateaukao** [comment]
glad to hear that it works for you.
